Iter13
SergeyGushan/lrn_go_url pull request #20
Opened 2023-12-25 22:42 UTC by SergeyGushan

2023-12-26 16:47 UTC, maxlyaptsev requested changes

2023-12-26 16:47 UTC, maxlyaptsev commented on internal/database/postgre_sql.go
> +var DBClient *sql.DB
не используем глобальные переменные
лучше сделать конструктор и вернуть ссылку на открытое соединение

2023-12-26 16:47 UTC, maxlyaptsev commented on internal/handlers/handlers.go
> +	}
этот код должен быть в middleware

2023-12-26 16:47 UTC, maxlyaptsev commented on internal/handlers/handlers.go
> +func Batch(res http.ResponseWriter, req *http.Request) {
```suggestion
func BatchCreate(res http.ResponseWriter, req *http.Request) {
```

2023-12-26 16:47 UTC, maxlyaptsev commented on internal/storage/url.go
> +		return "", fmt.Errorf("shortURL not found")
```suggestion
		return nil, fmt.Errorf("shortURL not found")
```
если возвращать ссылкой будет чуть удобней и правильней - т.к. пустая строка это тоже валидное значение

2023-12-26 16:47 UTC, maxlyaptsev commented on internal/url/url_services.go
> +package url
в названии файлов url_ лишнее

2023-12-26 18:35 UTC, SergeyGushan commented on internal/storage/url.go
> +		return "", fmt.Errorf("shortURL not found")
func (u *URL) GetOriginalURL(shortURL string) (string, error)   string возвращаемый тип

2023-12-26 18:35 UTC, SergeyGushan commented on internal/url/url_services.go
> +package url
+

2023-12-26 18:36 UTC, SergeyGushan commented on internal/handlers/handlers.go
> +func Batch(res http.ResponseWriter, req *http.Request) {
+

2023-12-26 18:36 UTC, SergeyGushan commented on internal/database/postgre_sql.go
> +var DBClient *sql.DB
+

2023-12-26 18:38 UTC, SergeyGushan commented on internal/handlers/handlers.go
> +	}
что бы это сделать я потратил дня три, я хз почему но не работает если перенести это в мидлвар

но попробую ещё

2023-12-27 15:09 UTC, maxlyaptsev commented on internal/storage/url.go
> +		return "", fmt.Errorf("shortURL not found")
Я вижу, и в этом заключается вопрос - если возможна ситуация когда не смогли найти url - почему возвращаемый тип string  в случае ошибки? Пустая строка это валидное значение. Если значение не найдено, правильно возвращать nil

2023-12-27 15:12 UTC, maxlyaptsev commented on internal/handlers/handlers.go
> +	}
Чтобы понять все довольно просто - нужно написать тесты. Потом в дебаг режиме проверить почему не проваливаемся в мидлвару. Возможно просто забыл ее подключить для ручки.

В общем первоначальная проблема - это отсутствие тестов

2023-12-27 15:19 UTC, maxlyaptsev commented on internal/handlers/handlers.go
> +func Save(res http.ResponseWriter, req *http.Request) {
Не увидел тесты для новых ручек. Нужно удостовериться что ручки сохраняют данные в бд, с помощью https://github.com/DATA-DOG/go-sqlmock например. Либо сделать мок на репозиторий. В целом достаточно убедиться что дергаются методы репозитория

2023-12-27 20:28 UTC, SergeyGushan commented on internal/storage/url.go
> +		return "", fmt.Errorf("shortURL not found")
как я в го могу указать тип string or null если в go нет такой возможности. Или я что-то упустил? И на сколько я вижу по обучению всегда проверяется валидность по error а не переменной значения

2023-12-27 20:31 UTC, SergeyGushan commented on internal/handlers/handlers.go
> +func Save(res http.ResponseWriter, req *http.Request) {
что такое ручки? в инкременте  с сохранением в файлах было прописано требование написать тесты. Для БД такого требования нету.

2023-12-28 15:54 UTC, maxlyaptsev commented on internal/storage/url.go
> +		return "", fmt.Errorf("shortURL not found")
Видимо упустил
```go
func (u *URL) GetOriginalURL(shortURL string) (*string, error) {
    return nil, fmt.Errorf("shortURL not found")
}
```

2023-12-30 10:13 UTC, merged