Iter15
SergeyGushan/lrn_go_url pull request #22
Opened 2024-01-15 08:12 UTC by SergeyGushan

2024-01-15 14:25 UTC, maxlyaptsev requested changes

2024-01-15 14:25 UTC, maxlyaptsev commented on internal/storage/database.go
> +		log.Fatal(err)
fatal не стоит - так мы можем остановить приложение. А еще нужно использовать нормальный логгер, который добавляли в предыдущих спринтах

2024-01-15 14:25 UTC, maxlyaptsev commented on internal/storage/file.go
> +	for _, record := range js.Items {
перебор всех записей - не очень эффективен. Для ускорения можно сделать индекс (https://pkg.go.dev/os#File.Seek)

Но а вообще я думаю файлы имеет смысл использовать только как дамп, для восстановления после остановки приложения. А при запуске выгружать все данные в память и работать уже с ними

2024-01-15 14:25 UTC, maxlyaptsev commented on internal/storage/database.go
> +	}
смысл задания в том чтобы делать запросы асинхронно - т.е. в данном случае нужно только положить url в канал и завершить функцию, отдать пользователю 200 статус.

В то же время должен работать воркер, который читает канал и делает всю работу по удалению

2024-01-15 14:29 UTC, maxlyaptsev commented on internal/storage/database.go
> +		}(url)
Тут нет контроля количества горутин - т.е. на каждый url будет своя горутина. Если запросов будет много и все с большим количеством записей - нет барьера, который будет регулировать нагрузку.

Если сделать как я написал выше воркер, который будет по-очереди читать канал - такой проблемы не будет. Но нужно подумать о размере канала т.к. большой буфер означает возможность потерять много данных

2024-01-15 15:55 UTC, SergeyGushan commented on internal/storage/file.go
> +	for _, record := range js.Items {
там так и сделано, при запуске грузится из файла в память и потом работает уже с переменной

2024-01-16 08:17 UTC, maxlyaptsev commented on internal/storage/file.go
> +	for _, record := range js.Items {
Тогда зачем перебирается вообще все айтемы? А если их там миллион?

2024-01-16 20:14 UTC, merged